<template>
  <div class="home">
    <div class="hero">
      <h1>Welcome to Luminous Orbs Jewels Store</h1>
      <p>Discover the finest selection of exquisite jewelry.</p>
      <router-link to="/products" class="btn btn-primary">Shop Now</router-link>
    </div>
  </div>
  <section>
    <div v-if="isLoading" class="loadingio-spinner-bean-eater-pgmqlvey3sh">
      <div class="ldio-ugtlj07j4f">
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
    <div v-for="p in Products" :key="p.prodID">
      <h2>{{ p.prodID }} - {{ p.prodName }}</h2>
      <p>{{ p.amount }}</p>
    </div>
  </section>
</template>

<script>
export default {
  data() {
    return {
      Products: [],
      isLoading: false,
    };
  },
  methods: {
    showProducts() {
      this.isLoading = true;

      fetch("https://node-project-fd1y.onrender.com/products")
        .then((response) => response.json())
        .then((data) => {
          this.Products = data;
          this.isLoading = false;
        });
    },
  },
  mounted() {
    this.showProducts();
  },
};
</script>

<style scoped>
/* Import Montserrat font */
@import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap");

.home {
  display: flex;
  justify-content: center;
  align-items: center;
  height: calc(100vh - 80px); /* Subtract navbar height */
  background-image: url("https://i.postimg.cc/PrFKVbkB/pxfuel-1.jpg");
  background-size: cover;
  background-position: center;
}

.hero {
  text-align: center;
  color: white;
}

.hero h1 {
  font-family: "Montserrat", sans-serif;
  font-size: 3rem;
  margin-bottom: 1rem;
}

.hero p {
  font-family: "Montserrat", sans-serif;
  font-size: 1.2rem;
  margin-bottom: 2rem;
}

.btn {
  font-family: "Montserrat", sans-serif;
  background-color: grey;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 5px;
  text-decoration: none;
  transition: background-color 0.3s ease;
}

.btn:hover {
  background-color: #ff3385;
}

/* Spinner */
@keyframes ldio-ugtlj07j4f-1 {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(-45deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
@keyframes ldio-ugtlj07j4f-2 {
  0% {
    transform: rotate(180deg);
  }
  50% {
    transform: rotate(225deg);
  }
  100% {
    transform: rotate(180deg);
  }
}
.ldio-ugtlj07j4f > div:nth-child(2) {
  transform: translate(-15px, 0);
}
.ldio-ugtlj07j4f > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #232323;
  animation: ldio-ugtlj07j4f-1 1s linear infinite;
  transform-origin: 60px 60px;
}
.ldio-ugtlj07j4f > div:nth-child(2) div:nth-child(2) {
  animation: ldio-ugtlj07j4f-2 1s linear infinite;
}
.ldio-ugtlj07j4f > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}
@keyframes ldio-ugtlj07j4f-3 {
  0% {
    transform: translate(190px, 0);
    opacity: 0;
  }
  20% {
    opacity: 1;
  }
  100% {
    transform: translate(70px, 0);
    opacity: 1;
  }
}
.ldio-ugtlj07j4f > div:nth-child(1) {
  display: block;
}
.ldio-ugtlj07j4f > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #ff0083;
  animation: ldio-ugtlj07j4f-3 1s linear infinite;
}
.ldio-ugtlj07j4f > div:nth-child(1) div:nth-child(1) {
  animation-delay: -0.67s;
}
.ldio-ugtlj07j4f > div:nth-child(1) div:nth-child(2) {
  animation-delay: -0.33s;
}
.ldio-ugtlj07j4f > div:nth-child(1) div:nth-child(3) {
  animation-delay: 0s;
}
.loadingio-spinner-bean-eater-pgmqlvey3sh {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-ugtlj07j4f {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ugtlj07j4f div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
